"""created db structure

Revision ID: 7b2b258dd09e
Revises: 
Create Date: 2024-08-29 12:57:30.431163

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b2b258dd09e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('board',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('board_name', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('board', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_board_id'), ['id'], unique=False)

    op.create_table('member',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('full_name', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('member', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_member_id'), ['id'], unique=False)

    op.create_table('card',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('card_name', sa.String(length=512), nullable=False),
    sa.Column('card_description', sa.String(length=1024), nullable=True),
    sa.Column('fk_card_association_board_id', sa.String(length=128), nullable=False),
    sa.ForeignKeyConstraint(['fk_card_association_board_id'], ['board.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('card', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_card_fk_card_association_board_id'), ['fk_card_association_board_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_card_id'), ['id'], unique=False)

    op.create_table('list',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('label_name', sa.String(length=128), nullable=False),
    sa.Column('board_id', sa.String(length=128), nullable=False),
    sa.ForeignKeyConstraint(['board_id'], ['board.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('list', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_list_board_id'), ['board_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_list_id'), ['id'], unique=False)

    op.create_table('card_member_association',
    sa.Column('fk_card_member_association_card_id', sa.String(length=128), nullable=False),
    sa.Column('fk_card_member_association_member_id', sa.String(length=128), nullable=False),
    sa.ForeignKeyConstraint(['fk_card_member_association_card_id'], ['card.id'], ),
    sa.ForeignKeyConstraint(['fk_card_member_association_member_id'], ['member.id'], ),
    sa.PrimaryKeyConstraint('fk_card_member_association_card_id', 'fk_card_member_association_member_id')
    )
    op.create_table('comment',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('commented_text', sa.String(length=1024), nullable=False),
    sa.Column('fk_comment_association_card_id', sa.String(length=128), nullable=False),
    sa.Column('fk_comment_association_member_id', sa.String(length=128), nullable=False),
    sa.Column('fk_comment_association_board_id', sa.String(length=128), nullable=False),
    sa.ForeignKeyConstraint(['fk_comment_association_board_id'], ['board.id'], ),
    sa.ForeignKeyConstraint(['fk_comment_association_card_id'], ['card.id'], ),
    sa.ForeignKeyConstraint(['fk_comment_association_member_id'], ['member.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_comment_fk_comment_association_board_id'), ['fk_comment_association_board_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_comment_fk_comment_association_card_id'), ['fk_comment_association_card_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_comment_fk_comment_association_member_id'), ['fk_comment_association_member_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_comment_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_comment_id'))
        batch_op.drop_index(batch_op.f('ix_comment_fk_comment_association_member_id'))
        batch_op.drop_index(batch_op.f('ix_comment_fk_comment_association_card_id'))
        batch_op.drop_index(batch_op.f('ix_comment_fk_comment_association_board_id'))

    op.drop_table('comment')
    op.drop_table('card_member_association')
    with op.batch_alter_table('list', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_list_id'))
        batch_op.drop_index(batch_op.f('ix_list_board_id'))

    op.drop_table('list')
    with op.batch_alter_table('card', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_card_id'))
        batch_op.drop_index(batch_op.f('ix_card_fk_card_association_board_id'))

    op.drop_table('card')
    with op.batch_alter_table('member', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_member_id'))

    op.drop_table('member')
    with op.batch_alter_table('board', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_board_id'))

    op.drop_table('board')
    # ### end Alembic commands ###
